[package]
name = "git-hooks-dispatch"
version = "0.1.0"
authors = ["Akira Ueda <ue@gol.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
env_logger = "0.9.0"
git2 = "0.13.20"
log = "0.4.14"
structopt = "0.3.22"
