name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup git user
      run: |
        git config --global user.email "ue@gol.com"
        git config --global user.name "UEDA Akira"

    - name: Install cargo-release
      run: |
        cargo install cargo-release

    - name: Cargo login
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: |
        cargo login ${CRATES_IO_TOKEN}

    - name: Release
      run: |
        cargo release --no-confirm
