name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Release
      run: |
        cargo login ${CRATES_IO_TOKEN}
        cargo release
